name: Schedule Test

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar evento
        run: 'echo "Evento: ${{ github.event_name }}"'

      - name: Mostrar fecha UTC
        run: date -u
